### ISSUE TITLE
正規表現の代わりにパーサコンビネータを使う

### ISSUE THREAD

**Issue by 4513ECHO** [gitdmnt/udamanami#2]
> `!1d100 コメント`的な用法が多くて、そのたびに使い方を説明しているのはかなりノイズだと思うので半角スペースの後は無視するなどの対応があると良いかも 

これを実現しやすくする目的

**Comment by gitdmnt** [comment]
#3 #4

**Comment by gitdmnt** [comment]
ファイル分割したいのでします

**Comment by 4513ECHO** [comment]
完了してるんでcloseします
